language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements-dev.txt --use-mirrors"
#  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
script:
  - py.test tests

