language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install . --use-mirrors -r requirements-dev.txt"
#  - "pip install --use-mirrors -r requirements-dev.txt"
#  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
script:
  - py.test tests
